config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  resources :resumes, :only => [:index]
  resources :sites

end

app/models/site.rb
class Site < ActiveRecord::Base
  has_attached_file :url_image, :styles => { :preview => "650x500", :thumb => "500x300"}, :s3_host_name => 's3-us-west-2.amazonaws.com'

  validates_attachment_content_type :url_image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user, :only => [:create, :update, :destroy]
  USERS = { "jgisin" => "jeff0708" }

  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
    @sites = Site.all.limit(4)
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to sites_path
    else
      redirect_to new_site_path
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      redirect_to sites_path
    else
      redirect_to edit_site_path(@site)
    end
  end

  def destroy
    @site = Site.find(params[:id])
    if @site.destroy
      redirect_to sites_path
    else
      redirect_to request.referrer
    end
  end

  private

  def site_params
    params.require(:site).permit(:title, :subheading, :description, :url,  :url_image)
  end

  private
  # The HTTP Digest version (better)
  def authenticate_user
    authenticate_or_request_with_http_digest do |username|
      USERS[username]
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @posts = MediumScraper.new
    @num_posts = 3#@posts.num_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JGisin</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resumes/index.html.erb
<div id="main" class="row">
  <div id="sidebar" class="col-sm-2">
    <nav id="sidebar-nav">
      <br/><br/><br/>
      <ul>
        <li><a class="animated bounceInLeft" id="side-home" href="/">Home</a>
        <li><a class="animated bounceInLeft" id="side-resume" href="<%= resumes_path %>">Resume</a>
        <li><a class="animated bounceInLeft" id="side-work" href="<%= sites_path %>">Portfolio</a>
        <!--<li><a class="animated bounceInLeft" id="side-contact" href="#">Contact</a>-->
      </ul>
    </nav>
  </div>

<div class="wrapper">
    <div class="sidebar-wrapper">
        <div class="profile-container">
            <%= image_tag "profile_thumb.jpg", class: "profile" %>
            <h1 class="name">Jeffrey Gisin</h1>
            <h3 class="tagline">Full Stack Developer</h3>
        </div><!--//profile-container-->

        <div class="contact-container container-block">
            <ul class="list-unstyled contact-list">
                <li class="email"><i class="fa fa-envelope"></i><a href="mailto: jgisin@gmail.com">jgisin@gmail.com</a></li>
                <li class="phone"><i class="fa fa-phone"></i><a href="tel:13039073523">303 907 3523</a></li>
                <li class="website"><i class="fa fa-globe"></i><a href="http://www.jgisin.com" target="_blank">Homepage</a></li>
                <li class="linkedin"><i class="fa fa-linkedin"></i><a href="https://www.linkedin.com/in/jgisin" target="_blank">LinkedIn</a></li>
                <li class="github"><i class="fa fa-github"></i><a href="https://github.com/jgisin" target="_blank">Github</a></li>
                <li class="twitter"><i class="fa fa-twitter"></i><a href="https://twitter.com/tempest280" target="_blank">Twitter</a></li>
            </ul>
        </div><!--//contact-container-->
        <div class="education-container container-block">
            <h2 class="container-block-title">Education</h2>
            <div class="item">
                <h4 class="degree">Electrical Engineering</h4>
                <h5 class="meta">University of Colorado at Denver</h5>
                <div class="time">2012</div>
            </div><!--//item-->
            <div class="item">
                <h4 class="degree">Viking Code School</h4>
                <h5 class="meta">Coding Bootcamp</h5>
                <div class="time">2016</div>
            </div><!--//item-->
        </div><!--//education-container-->

        <div class="languages-container container-block">
            <h2 class="container-block-title">Languages</h2>
            <ul class="list-unstyled interests-list">
                <li>English <span class="lang-desc">(Native)</span></li>
                <li>Russian <span class="lang-desc">(Fluent)</span></li>
            </ul>
        </div><!--//interests-->

        <div class="interests-container container-block">
            <h2 class="container-block-title">Interests</h2>
            <ul class="list-unstyled interests-list">
                <li>Hockey</li>
                <li>Skiing</li>
                <li>Travel</li>
            </ul>
        </div><!--//interests-->

    </div><!--//sidebar-wrapper-->

    <div class="main-wrapper">

        <section class="section summary-section">
            <h2 class="section-title"><i class="fa fa-user"></i>Career Profile</h2>
            <div class="summary">
                <p>Talented full stack web developer with strong foundation in object oriented programming and web design. Articulate and comfortable in varied teamwork heavy environments. Dedicated to embracing and learning new technologies and modern methodologies.</p>
            </div><!--//summary-->
        </section><!--//section-->

        <section class="section experiences-section">
            <h2 class="section-title"><i class="fa fa-briefcase"></i>Experiences</h2>

            <div class="item">
                <div class="meta">
                    <div class="upper-row">
                        <h3 class="job-title">Software Developer</h3>
                        <div class="time">2016-Present</div>
                    </div><!--//upper-row-->
                    <div class="company">Cloverhound</div>
                </div><!--//meta-->
                <div class="details">
                    <p>Software Engineer working on call center and telephony cloud based software and Cisco  API integrations</p>
                </div><!--//details-->
            </div><!--//item-->

            <div class="item">
                <div class="meta">
                    <div class="upper-row">
                        <h3 class="job-title">Electrical Designer/ IT Manager</h3>
                        <div class="time">2012-2015</div>
                    </div><!--//upper-row-->
                    <div class="company">RG Engineering Consultants - Denver, CO</div>
                </div><!--//meta-->
                <div class="details">
                    <p>Maintained organization's web presence and IT infrastructure while continuing duties as Electrical Designer. Managed FTP file sharing, project file backups, and company knowledgebase.</p>
                </div><!--//details-->
            </div><!--//item-->

            <div class="item">
                <div class="meta">
                    <div class="upper-row">
                        <h3 class="job-title">Electrical Designer</h3>
                        <div class="time">2010-2012</div>
                    </div><!--//upper-row-->
                    <div class="company">Cator Ruma and Associates - Lakewood, CO</div>
                </div><!--//meta-->
                <div class="details">
                    <p>Created company knowledge-base with MySQL backed Atlassian Confluence wiki-site in addition to regular Engineering duties. Served as software troubleshooter to other employees.</p>

                </div><!--//details-->
            </div><!--//item-->

            <div class="item">
                <div class="meta">
                    <div class="upper-row">
                        <h3 class="job-title">Co-Owner</h3>
                        <div class="time">2003-2006</div>
                    </div><!--//upper-row-->
                    <div class="company">Jazz Computers</div>
                </div><!--//meta-->
                <div class="details">
                    <p>Started a boutique custom PC building company. Designed e-commerce website and brand media. Eventually merged with Aevium Web Marketing firm and helped build the Aevium Technologies brand.</p>
                </div><!--//details-->
            </div><!--//item-->

        </section><!--//section-->

        <section class="section projects-section">
            <h2 class="section-title"><i class="fa fa-archive"></i>Projects</h2>
            <div class="intro">
                <p>Here is a list of relevant project work. The links take you to the Github repositories for a better sampling of my coding style. For application demonstrations, please visit my portfolio.</p>
            </div><!--//intro-->
            <div class="item">
                <span class="project-title"><a href="https://github.com/jgisin/danebook">Danebook</a></span> - <span class="project-tagline">A social networking site with commenting, liking posts, photo uploads (AWS), email notifications (SendGrid), test suite (RSpec, Capybara), backed by a Postgres database.</span>

            </div><!--//item-->
            <div class="item">
                <span class="project-title"><a href="https://github.com/jgisin/pokequiz" target="_blank">PokeQuiz</a></span> -
                <span class="project-tagline">A hack-a-thon style app built by me and a small team in 36 hours. Tested (RSpec), utilizes a web scraper and third party API, custom logging, email notifications, AWS file uploads, twitter-style user following, leaderboard stats.</span>
            </div><!--//item-->
            <div class="item">
                <span class="project-title"><a href="https://github.com/jgisin/project_viking_store" target="_blank">Viking Store</a></span> - <span class="project-tagline">E-commerce style application with shopping carts, order/product tracking, admin dashboard, admin portal.</span>
            </div><!--//item-->
            <div class="item">
                <span class="project-title"><a href="https://github.com/jgisin/elec_calcs" target="_blank">Elec Calcs</a></span> - <span class="project-tagline">Computation and document creation for Electrical Engineers. Built on Rails with ajax partial rendering. </span>
            </div><!--//item-->
        </section><!--//section-->

        <section class="skills-section section">
            <h2 class="section-title"><i class="fa fa-rocket"></i>Skills &amp; Proficiency</h2>
            <div class="skillset">
                <div class="item">
                    <h3 class="level-title">Ruby</h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="98%">
                        </div>
                    </div><!--//level-bar-->
                </div><!--//item-->

                <div class="item">
                    <h3 class="level-title">Javascript &amp; jQuery</h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="90%">
                        </div>
                    </div><!--//level-bar-->
                </div><!--//item-->

                <div class="item">
                    <h3 class="level-title">Angular</h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="90%">
                        </div>
                    </div><!--//level-bar-->
                </div><!--//item-->

                <div class="item">
                    <h3 class="level-title">ReactJS</h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="90%">
                        </div>
                    </div><!--//level-bar-->
                </div><!--//item-->

                <div class="item">
                    <h3 class="level-title">HTML5 &amp; CSS</h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="98%">
                        </div>
                    </div><!--//level-bar-->
                </div><!--//item-->

                <div class="item">
                    <h3 class="level-title">Ruby on Rails</h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="98%">
                        </div>
                    </div><!--//level-bar-->
                </div><!--//item-->

                <div class="item">
                    <h3 class="level-title">Sketch &amp; Photoshop</h3>
                    <div class="level-bar">
                        <div class="level-bar-inner" data-level="50%">
                        </div>
                    </div><!--//level-bar-->
                </div><!--//item-->

            </div>
        </section><!--//skills-section-->

    </div><!--//main-body-->
</div>



<!-- custom js -->
<script type="text/javascript" src="assets/js/main.js"></script>
</div>

app/views/sites/_form.html.erb
<%= form_for @site do |site_field| %>

    <%= site_field.label :title, class: 'subtext'%>
    <%= site_field.text_field :title, class: 'form-control'%><br/>
    <%= site_field.label :subheading, class: 'subtext'%>
    <%= site_field.text_field :subheading, class: 'form-control' %><br/>
    <%= site_field.label :description, class: 'subtext'%>
    <%= site_field.text_field :description, class: 'form-control' %><br/>
    <%= site_field.label :url, class: 'subtext'%>
    <%= site_field.text_field :url, class: 'form-control' %><br/>
    <%= site_field.label :url_image, class: 'subtext'%>
    <%= site_field.file_field :url_image, class: 'form-control' %><br/>
    <%= site_field.submit "Create Site", class: 'btn btn-lg btn-primary' %>

    <% if !@site.id.nil? %>
      <%= link_to "Delete Project", site_path(@site), class: 'btn btn-lg btn-danger', method: :delete %>
    <% end %>

<% end %>

app/views/sites/edit.html.erb
<%= render partial: 'form' %>

app/views/sites/index.html.erb
<div id="sidebar" class="col-sm-2">
  <nav id="sidebar-nav">
    <br/><br/><br/>
    <ul>
      <li><a class="animated bounceInLeft" id="side-home" href="/">Home</a>
      <li><a class="animated bounceInLeft" id="side-resume" href="<%= resumes_path %>">Resume</a>
      <li><a class="animated bounceInLeft" id="side-work" href="<%= sites_path %>">Portfolio</a>
      <!--<li><a class="animated bounceInLeft" id="side-contact" href="#">Contact</a>-->
    </ul>
  </nav>
</div>

  <h1 class="subtext text-center">Projects</h1><hr><br/><br/>
  <div class="col-sm-10">
    <% @sites.each do |site| %>
    <div class="col-sm-4 portrow">
      <a href="<%= site_path(site) %>">
        <%= image_tag site.url_image, class: 'img-responsive portfolio-item' %>
      </a><br/>
      <p class="subtext text-center" style="font-size: 24px"><%= site.title %></p>
    </div>
  <% end %>
  </div>

app/views/sites/new.html.erb
<%= render partial: 'form' %>

app/views/sites/show.html.erb
<div class="container">

  <!-- Portfolio Item Heading -->
  <div class="row">

    <div class="col-lg-10 col-xs-offset-2">

      <h1 class="subtext"><%= @site.title %>
        <small><%= @site.subheading %></small>
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <!-- Portfolio Item Row -->
  <div class="row">
    <div id="main" class="row">

      <div id="sidebar" class="col-sm-2">
        <nav id="sidebar-nav">
          <br/><br/><br/>
          <ul>
            <li><a class="animated bounceInLeft" id="side-home" href="/">Home</a>
            <li><a class="animated bounceInLeft" id="side-resume" href="<%= resumes_path %>">Resume</a>
            <li><a class="animated bounceInLeft" id="side-work" href="<%= sites_path %>">Portfolio</a>
            <!--<li><a class="animated bounceInLeft" id="side-contact" href="#">Contact</a>-->
          </ul>
        </nav>
      </div>

    <div class="col-md-6">
    <a href="http://<%= @site.url %>">
      <%= image_tag @site.url_image(:preview) %>
    </a>
    </div>

    <div class="col-md-4" id="content">
      <h3 class="subtext">Project Description</h3>
      <p><%= @site.description %></p>
    </div>

  </div>
  <!-- /.row -->

  <!-- Related Projects Row -->
  <div class="row">

    <div class="col-lg-9 col-xs-offset-2">
      <h3 class="subtext">Related Projects</h3>
      <hr>
    </div>
    <div class="col-sm-10 col-sm-offset-2">
      <% @sites.each do |site| %>
          <% unless site.id == params[:id].to_i %>
            <div class="col-sm-3 col-xs-6">
              <a href="<%= site_path(site) %>">
                <%= image_tag site.url_image, class: 'img-responsive portfolio-item' %>
              </a><br/>
              <p class="subtext text-center" style="font-size: 24px"><%= site.title %></p>
            </div>
          <% end %>
      <% end %>
    </div>
  <!-- /.row -->

    </div>
  </div>
</div>
  <!-- Footer -->
<footer class="text-center">
  <hr>
  <a href="mailto: jgisin@gmail.com" class="btn btn-social btn-google"><span class="fa fa-google"></span>jgisin@gmail.com</a></li>
  <a href="tel:13039073523" class="btn btn-social btn-primary"><span class="fa fa-phone"></span>303 907 3523</a>
  <a href="http://www.jgisin.com" target="_blank" class="btn btn-social btn-warning"><span class="fa fa-globe"></span>Homepage</a></li>
  <a href="https://www.linkedin.com/in/jgisin" target="_blank" class="btn btn-social btn-linkedin"><span class="fa fa-linkedin"></span>LinkedIn</a>
  <a href="https://github.com/jgisin" target="_blank" class="btn btn-social btn-github"><span class="fa fa-github"></span>Github</a>
  <a href="https://twitter.com/tempest280" target="_blank" class="btn btn-social btn-twitter"><span class="fa fa-twitter"></span>Twitter</a></footer>

app/views/static_pages/index.html.erb
<div id="header" class="row text-center">
  <div id="logo">
        <span id="danger">
          <span class="jj animated bounceInDown">J</span>
          <span class="je animated bounceInDown">E</span>
          <span class="jf animated bounceInDown">F</span>
          <span class="jff animated bounceInDown">F</span>
          <span class="jr animated bounceInDown">R</span>
          <span class="jee animated bounceInDown">E</span>
          <span class="jy animated bounceInDown">Y</span>
        </span>&nbsp;
        <span id="zone">
          <span class="gg animated bounceInDown">G</span>
          <span class="gi animated bounceInDown">I</span>
          <span class="gs animated bounceInDown">S</span>
          <span class="gii animated bounceInDown">I</span>
          <span class="gn animated bounceInDown">N</span>
        </span>
  </div>

  <nav class="animated bounceInLeft" id="main-nav">
    <!--<ul class="list-unstyled list-inline">-->
    <!--<li><a id="demo-1" class="animated btn btn-danger" href="index.html.erb">Demo 1</a></li>-->
    <!--<li><a id="demo-2" class="animated btn btn-danger" href="two.html">Demo 2</a></li>-->
    <!--<li><a id="demo-3" class="animated btn btn-danger" href="three.html">Demo 3</a></li>-->
    <!--</ul>-->
    <span class="subtext"> Full Stack Web Developer </span>
  </nav>
</div>

<div id="main" class="row">
  <div id="sidebar" class="col-sm-3">
    <nav id="sidebar-nav">
      <br/><br/><br/>
      <ul>
        <li><a id="side-home" class="animated bounceInLeft" href="#">Home</a>
        <li><a id="side-resume" class="animated bounceInLeft" href="<%= resumes_path %>">Resume</a>
        <li><a id="side-work" class="animated bounceInLeft" href="<%= sites_path %>">Portfolio</a>
        <!--<li><a id="side-contact" class="animated bounceInLeft" href="#">Contact</a>-->
      </ul>
    </nav>
  </div>

  <div id="content" class="animated bounceInUp col-sm-8">

    <div class="row">

      <div class="col-sm-9 col-sm-offset-1">
        <h4 class="subtext">Recent Posts</h4>
        <hr>
        <!--<br/>-->
        <!--<p>Welcome to my personal showcase and portfolio. I hope to showcase my skills-->
          <!--in both the front end flash, and back end structure. Everything you see is built-->
          <!--with a Ruby on Rails backend, connected to a variety of front-end platforms. </p>-->

        <!--<p>Poke around and see if you can find the easter eggs scattered throughout. Find-->
          <!--enough and you may unlock a little bonus content!</p>-->

        <% @num_posts.times do |index| %>
            <h3><%= @posts.post(index)[:title] %></h3>
            <p><%= @posts.post(index)[:text] %></p>
            <a href="<%= @posts.post(index)[:link] %>">Read More...</a>
        <% end %>
      </div>

      <!--<div class="col-sm-3 col-sm-offset-1 text-right">-->
        <!--<h3>Contact Me</h3><hr>-->

          <!--<a href="mailto: jgisin@gmail.com" class="btn btn-block btn-social btn-google"><span class="fa fa-google"></span>jgisin@gmail.com</a></li>-->
          <!--<a href="tel:13039073523" class="btn btn-block btn-social btn-primary"><span class="fa fa-phone"></span>303 907 3523</a>-->
          <!--<a href="http://www.jgisin.com" target="_blank" class="btn btn-block btn-social btn-warning"><span class="fa fa-globe"></span>Homepage</a></li>-->
          <!--<a href="https://www.linkedin.com/in/jgisin" target="_blank" class="btn btn-block btn-social btn-linkedin"><span class="fa fa-linkedin"></span>LinkedIn</a>-->
          <!--<a href="https://github.com/jgisin" target="_blank" class="btn btn-block btn-social btn-github"><span class="fa fa-github"></span>Github</a>-->
          <!--<a href="https://twitter.com/tempest280" target="_blank" class="btn btn-block btn-social btn-twitter"><span class="fa fa-twitter"></span>Twitter</a>-->

      <!--</div>-->

    </div>
  </div>
</div>

<footer class="text-center">
  <hr>
  <a href="mailto: jgisin@gmail.com" class="btn btn-social btn-google"><span class="fa fa-google"></span>jgisin@gmail.com</a></li>
  <a href="tel:13039073523" class="btn btn-social btn-primary"><span class="fa fa-phone"></span>303 907 3523</a>
  <a href="http://www.jgisin.com" target="_blank" class="btn btn-social btn-warning"><span class="fa fa-globe"></span>Homepage</a></li>
  <a href="https://www.linkedin.com/in/jgisin" target="_blank" class="btn btn-social btn-linkedin"><span class="fa fa-linkedin"></span>LinkedIn</a>
  <a href="https://github.com/jgisin" target="_blank" class="btn btn-social btn-github"><span class="fa fa-github"></span>Github</a>
  <a href="https://twitter.com/tempest280" target="_blank" class="btn btn-social btn-twitter"><span class="fa fa-twitter"></span>Twitter</a></footer>